# Generated by Django 4.1.4 on 2023-01-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sale_permission',
            field=models.CharField(choices=[('own', 'own'), ('all', 'all'), ('admin', 'admin')], default='admin', max_length=100),
        ),
    ]
