# Generated by Django 4.1.4 on 2023-01-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_sale_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purchase_permission',
            field=models.CharField(choices=[('none', 'none'), ('own', 'own'), ('all', 'all'), ('admin', 'admin')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sale_permission',
            field=models.CharField(choices=[('none', 'none'), ('own', 'own'), ('all', 'all'), ('admin', 'admin')], default='none', max_length=100),
        ),
    ]
