# Generated by Django 4.1.4 on 2023-01-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='for_stock',
            field=models.BooleanField(default=True, help_text='Show on stock'),
        ),
        migrations.AddField(
            model_name='category',
            name='for_website',
            field=models.BooleanField(default=False, help_text='Show on website'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inv.category', verbose_name='Parent'),
        ),
    ]
