# Generated by Django 4.1.4 on 2023-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elr', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
