# Generated by Django 4.1.4 on 2023-01-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='include_price',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Include Price'),
        ),
        migrations.AddField(
            model_name='tax',
            name='typeTax',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], default='sale', max_length=64),
        ),
    ]
