# Generated by Django 4.1.4 on 2023-01-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0011_country_code'),
        ('acc', '0002_tax_include_price_tax_typetax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='con.country', verbose_name='Country'),
        ),
    ]
