# Generated by Django 4.1.4 on 2023-01-05 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0011_country_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acc', '0003_tax_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('alias', models.CharField(max_length=40, verbose_name='Alias')),
                ('symbol', models.CharField(max_length=15, verbose_name='Symbol')),
                ('iso', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('before', 'before to amount'), ('after', 'after to amount')], default='after', max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='con.country')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
