# Generated by Django 4.1.4 on 2023-01-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='show_blog',
            field=models.BooleanField(default=False, verbose_name='Show Blog'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_price',
            field=models.BooleanField(default=True, verbose_name='Show price'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_shop',
            field=models.BooleanField(default=False, verbose_name='Show Shop'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='under_construction',
            field=models.BooleanField(default=False, verbose_name='Under Construction'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='user_register',
            field=models.BooleanField(default=False, verbose_name='User Register'),
        ),
    ]
