# Generated by Django 4.1.4 on 2023-01-05 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conf', '0003_alter_configuration_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('interval_type', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('day', 'Day'), ('work_day', 'Work Day'), ('weeks', 'Weeks'), ('month', 'Month')], default='hours', max_length=64)),
                ('model_name', models.CharField(max_length=40, verbose_name='Model')),
                ('function', models.CharField(max_length=40, verbose_name='Function')),
                ('number_call', models.IntegerField(default=-1, verbose_name='Numer of calls')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cron',
                'verbose_name_plural': 'Crons',
                'ordering': ['name'],
            },
        ),
    ]
