# Generated by Django 4.1.4 on 2023-01-06 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conf', '0009_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('prefix', models.CharField(default='default', max_length=40, verbose_name='Prefix')),
                ('padding', models.PositiveIntegerField(default=4, verbose_name='padding')),
                ('initial', models.PositiveIntegerField(default=1, verbose_name='initial')),
                ('increment', models.PositiveIntegerField(default=1, verbose_name='increment')),
                ('reset', models.PositiveIntegerField(blank=True, null=True, verbose_name='reset')),
                ('last', models.PositiveIntegerField(editable=False, verbose_name='Last')),
                ('next_val', models.PositiveIntegerField(verbose_name='Next')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sequence',
                'verbose_name_plural': 'sequences',
            },
        ),
    ]
