# Generated by Django 4.1.4 on 2023-01-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0010_rename_parent_id_contact_state_id'),
        ('sal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='amount_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='amount_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='amount_untaxed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='partner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='con.contact', verbose_name='Partner'),
        ),
    ]
