# Generated by Django 4.1.4 on 2023-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sal', '0002_saleorder_amount_discount_saleorder_amount_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('done', 'Done'), ('cancel', 'Cancel')], default='draft', max_length=64),
        ),
    ]
