# Generated by Django 4.1.4 on 2023-01-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0011_country_code'),
        ('sal', '0004_saleorder_company_id_alter_saleorder_partner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_company', to='con.contact', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='partner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='so_partner', to='con.contact', verbose_name='Partner'),
        ),
    ]
