# Generated by Django 4.1.4 on 2023-01-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_product_category_id'),
        ('sal', '0010_saleorderline_description_saleorderline_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderline',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivered'),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='invoiced_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Invoiced'),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='uom_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.uom', verbose_name='UOM'),
        ),
    ]
