# Generated by Django 4.1.4 on 2023-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sal', '0011_saleorderline_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
    ]
