# Generated by Django 4.1.4 on 2023-01-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_journal'),
        ('sal', '0012_saleorderline_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleorderline',
            options={'ordering': ['pk'], 'verbose_name': 'Sale order line', 'verbose_name_plural': 'Sale orders line'},
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='amount_exempt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='amount_tax_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='amount_tax_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='amount_tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='amount_untaxed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount un'),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='tax_id',
            field=models.ManyToManyField(blank=True, to='acc.tax', verbose_name='Tax'),
        ),
    ]
