# Generated by Django 4.1.4 on 2023-01-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0004_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='con.country', verbose_name='Country'),
        ),
    ]
