# Generated by Django 4.1.4 on 2023-01-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0008_contact_own_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='state_id',
            new_name='parent_id',
        ),
    ]
