# Generated by Django 4.1.4 on 2023-01-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0010_rename_parent_id_contact_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
